# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mHdX99PSIJJrDZGJmWshLCEli3YOyFFd
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

datasheet = pd.read_csv("/content/yametezaddy.csv")
x = np.array(datasheet.iloc[:,0:1])
y = np.array(datasheet.iloc[:,1:2])

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = 1)

from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)

plt.scatter(x_train, y_train, color='red')
plt.plot(x_train, lr.predict(x_train), color='blue')
plt.title("Best Fit Line")
plt.xlabel('X-axis')
plt.ylabel("Y-axis")
plt.show()

print("y = "+str(*lr.coef_[0])+"*x+"+str(lr.intercept_[0]))